### ISSUE TITLE
No examples appear in the docs 

### ISSUE THREAD

**Issue by DDKatch** [joeldrapper/phlex.fun#21]
Am I the only one who doesn't see any examples in the docs?

<img width="1305" alt="Screenshot 2023-08-25 at 12 58 10" src="https://github.com/joeldrapper/phlex.fun/assets/14095146/64df4491-4aac-448d-977a-fd9884832c35">
<img width="1310" alt="Screenshot 2023-08-25 at 13 01 04" src="https://github.com/joeldrapper/phlex.fun/assets/14095146/92b0bd9c-f398-4f82-97d4-81a92bc23524">

**Comment by joeldrapper** [comment]
Oh no, this doesn’t look right. Which browser are you using?

**Comment by DDKatch** [comment]
@joeldrapper I'm using  Google Chrome Version 115.0.5790.170 (Official Build) (arm64)
Maybe one of my extensions is messing with it 🤔

**Comment by DDKatch** [comment]
It really works with Firefox and Safari

**Comment by DDKatch** [comment]
Chrome incognito mode works as well

**Comment by DDKatch** [comment]
even Chromium Version 115.0.5745.0 (Developer Build) (arm64)
works.

Looks like something is definitely wrong with my browser 😅

**Comment by DDKatch** [comment]
That's unreal 😅 
html was actually received but not rendered. wtf?
<img width="1727" alt="Screenshot 2023-08-25 at 19 47 52" src="https://github.com/joeldrapper/phlex.fun/assets/14095146/a2875a59-85dc-4a1c-89e8-b3cfaafec36b">

**Comment by DDKatch** [comment]
Found the culprit
<img width="417" alt="Screenshot 2023-08-25 at 19 57 13" src="https://github.com/joeldrapper/phlex.fun/assets/14095146/ad35c53f-ff1a-48b8-9ea1-edc7ee7f3cb1">

When it shifts to night mode - the elements disappear. And it stays this way even after shifting it back to daylight mode
